require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'

target 'ViroReact' do
    config = use_native_modules!
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_react_native!(:path => config["reactNativePath"])

  # Pods for ViroReact
  use_flipper!
   post_install do |installer|
     flipper_post_install(installer)
   end

end

target 'ViroReact_release_tests' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  inherit! :search_paths
  # Pods for ViroReact_release_tests

end

target 'ViroReact_static_lib' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  inherit! :search_paths
  # Pods for ViroReact_static_lib


end
